- type: job
  id: StationRepresentative
  name: job-name-sr
  description: job-description-sr
  playTimeTracker: JobStationRepresentative
  icon: JobIconHeadOfPersonnel
  startingGear: StationRepresentativeGear
  supervisors: job-supervisors-centcom
  displayWeight: 10
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobStationTrafficController
      time: 2h
    - !type:RoleTimeRequirement
      role: JobFrontierSecurityGuard
      time: 5h
  access:
  - FrontierCommand
  - StationRepresentative
  - FrontierPostOffice
  - FrontierEngineering
  - FrontierSecurity
  - FrontierJanitor
  - Court
  - Attorney
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: StationRepresentativeGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: SRPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboardThreePapers
    eyes: ClothingEyesHudCommand
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: StationRepresentativeChameleonOutfit
  job: StationRepresentative
  hasMindShield: true
  equipment:
    head: ClothingHeadHatHopcap
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskNeckGaiterRed
    neck: ClothingNeckCloakHop
    outerClothing: ClothingOuterWinterHoP

- type: entity
  parent: HoPPDA
  id: SRPDA
  components:
  - type: Pda
    id: SRIDCard
