using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Eclipse.Maps.Sectors;
using Content.Shared._Eclipse.Stargate;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;

namespace Content.Client._Eclipse.Map.Sectors.UI;

[GenerateTypedNameReferences]
public sealed partial class SectorsMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private EntityUid? _consoleEntity;

    public event Action? OnStargateJumpButton;

    public SectorsMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StargateJumpButton.OnPressed += _ => OnStargateJumpButton?.Invoke();
    }

    public void SetConsole(EntityUid uid)
    {
        _consoleEntity = uid;
        SectorsMap.SetConsole(uid);
    }

    public void UpdateState(SectorsMapBoundUserInterfaceState cast)
    {
        SectorsMap.UpdateState(cast);

        var closestBody = _entManager.GetEntity(cast.ClosestBody);
        UpdateStargatePanel(closestBody);
    }

    public void UpdateStargatePanel(EntityUid? closestBody)
    {
        if (!_entManager.TryGetComponent<StargateComponent>(closestBody, out var gate))
        {
            StargateJumpButton.Disabled = true;
            return;
        }

        StargateJumpButton.Disabled = false;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
    }
}
