using Content.Client.Shuttles.UI;
using Content.Shared._Eclipse.Map.Celestial;
using Content.Shared._Eclipse.Maps.Sectors;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.UI.MapObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Maths;
using Robust.Shared.Physics.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._Eclipse.Map.Sectors.UI;

[GenerateTypedNameReferences]
public sealed partial class SectorsMapControl : BaseShuttleControl
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IInputManager _inputs = default!;
    private readonly SharedTransformSystem _transform;
    private readonly EntityLookupSystem _lookup;
    private readonly SpriteSystem _sprite;

    protected override bool Draggable => true;

    private readonly Font _font;
    private readonly Color _gridColor = new Color(255, 255, 255, 25);

    private Dictionary<Vector2, MapSectorData> _sectorsData = new();
    private EntityUid? _consoleEntity;
    private EntityUid? _closestBody;

    public SectorsMapControl() : base(4f, 512f, 512f)
    {
        RobustXamlLoader.Load(this);
        _transform = EntManager.System<SharedTransformSystem>();
        _lookup = EntManager.System<EntityLookupSystem>();
        _sprite = EntManager.System<SpriteSystem>();
        var cache = IoCManager.Resolve<IResourceCache>();

        _font = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 12);
    }

    public void UpdateState(SectorsMapBoundUserInterfaceState cast)
    {
        _sectorsData = cast.Sectors;
        _closestBody = _entityManager.GetEntity(cast.ClosestBody);
    }

    public void SetConsole(EntityUid uid)
    {
        _consoleEntity = uid;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var screenCenter = PixelSize / 2f;
        var zoom = ActualRadarRange / 256f;
        var offset = new Vector2(Offset.X, -Offset.Y) / zoom;
        var mapToScreen = Matrix3Helpers.CreateTransform(screenCenter - offset, 0f, new Vector2(1f, -1f) / zoom);

        var unitSize = 120f;

        handle.DrawRect(new UIBox2(Vector2.Zero, PixelSize), Color.Black);

        // Draw grid
        int gridSize = 10;
        for (int i = -gridSize; i <= gridSize; i++)
        {
            handle.DrawLine(Vector2.Transform(new Vector2(-gridSize * unitSize, i * unitSize), mapToScreen),
                            Vector2.Transform(new Vector2(gridSize * unitSize, i * unitSize), mapToScreen),
                            _gridColor);

            handle.DrawLine(Vector2.Transform(new Vector2(i * unitSize, -gridSize * unitSize), mapToScreen),
                            Vector2.Transform(new Vector2(i * unitSize, gridSize * unitSize), mapToScreen),
                            _gridColor);
        }

        // Draw sectors and lines between them
        foreach (var sector in _sectorsData)
        {
            var position = Vector2.Transform(sector.Key * unitSize, mapToScreen);
            var radius = 30f / zoom;

            handle.DrawCircle(position, radius, Color.White, false);

            if (_consoleEntity == null || _transform.GetMapId(_consoleEntity.Value) == sector.Value.MapId)
            {
                handle.DrawCircle(position, radius, Color.White.WithAlpha(5), true);
                DrawPointer(handle, position, radius + 5f);
                if (zoom <= 0.25f)
                    DrawSectorContent(handle, position, 10000f, radius, sector.Value.MapId);
            }
            else
                handle.DrawCircle(position, radius, Color.White.WithAlpha(10), true);


            foreach (var connection in sector.Value.Connections)
            {
                var connectionPosition = Vector2.Transform(connection * unitSize, mapToScreen);
                var direction = Vector2.Normalize(connectionPosition - position);

                handle.DrawLine(position + direction * (radius + 5f), connectionPosition - direction * (radius + 5f), Color.White);
            }

            handle.DrawString(_font, position + new Vector2(0.8f, 0.8f) * radius, sector.Value.Name, Color.White);
        }
    }

    private void DrawSectorContent(DrawingHandleScreen handle, Vector2 origin,
                                   float radius, float uiRadius, MapId mapId)
    {
        HashSet<Entity<CelestialBodyComponent>> bodies = new();
        _lookup.GetEntitiesOnMap(mapId, bodies);

        var scale = uiRadius / radius;

        // Draw celestial bodies
        foreach (var entity in bodies)
        {
            var worldPosition = _transform.GetWorldPosition(entity);
            var position = origin + worldPosition * scale * new Vector2(1f, -1f);

            handle.DrawCircle(position, entity.Comp.Radius * scale, entity.Comp.RadarColor, false);
            handle.DrawCircle(position, entity.Comp.Radius * scale, entity.Comp.RadarColor.WithAlpha(20));

            var icon = _sprite.Frame0(entity.Comp.RadarIcon);
            handle.DrawTexture(icon, position - icon.Size / 2f, entity.Comp.RadarColor);

            if (!_entityManager.TryGetComponent<MetaDataComponent>(entity, out var meta))
                continue;

            handle.DrawString(_font, position + new Vector2(icon.Width / 2f, -icon.Height / 2f), meta.EntityName, entity.Comp.RadarColor);
        }

        // Draw our shuttle
        if (_consoleEntity == null)
            return;

        var grid = _transform.GetGrid(_consoleEntity.Value);
        if (grid == null)
            return;
        var shuttlePosition = origin + _transform.GetWorldPosition(grid.Value) * scale * new Vector2(1f, -1f);
        var shuttleRotation = -_transform.GetWorldRotation(grid.Value);

        List<Vector2> vertices = new();
        vertices.Add(shuttlePosition + shuttleRotation.RotateVec(new Vector2(0f, 6f)));
        vertices.Add(shuttlePosition + shuttleRotation.RotateVec(new Vector2(8f, 8f)));
        vertices.Add(shuttlePosition + shuttleRotation.RotateVec(new Vector2(0f, -10f)));
        vertices.Add(shuttlePosition + shuttleRotation.RotateVec(new Vector2(-8f, 8f)));
        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, Color.White.WithAlpha(30));
        handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, vertices, Color.White);

        // And draw marker if shuttle above any body
        if (_closestBody != null)
        {
            var worldPosition = _transform.GetWorldPosition(_closestBody.Value);
            var position = origin + worldPosition * scale * new Vector2(1f, -1f);

            DrawPointer(handle, position, 20f);
        }
    }

    private void DrawPointer(DrawingHandleScreen handle, Vector2 position, float radius)
    {
        Angle animOffset = new Angle(_timing.CurTime.TotalSeconds * 0.5f);

        int count = 3;
        Angle offset = Math.PI * 2f / count;

        for (int i = 0; i < count; i++)
        {
            var angle = animOffset + offset * i;
            var frontPoint = angle.RotateVec(new Vector2(0f, radius));
            var backPoint = angle.RotateVec(new Vector2(0f, radius + 10f));
            var direction = (frontPoint - backPoint).Normalized();

            var vertices = new List<Vector2>();
            vertices.Add(frontPoint + position);
            vertices.Add(backPoint + Angle.FromDegrees(90f).RotateVec(direction) * 20f + position);
            vertices.Add(backPoint + Angle.FromDegrees(90f).RotateVec(direction) * -20f + position);
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, vertices, Color.White.WithAlpha(20));
            handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, vertices, Color.White);
        }
    }
}
